### ISSUE TITLE
jdk1.8  Exception in thread "main" java.io.EOFException: Unexpected end of ZIP input stream

### ISSUE THREAD

**Issue by huliangshan123** [theautonomy/bouncycastle-gpg-example#4]
Exception in thread "main" java.io.EOFException: Unexpected end of ZIP input stream
	at org.bouncycastle.openpgp.PGPCompressedData$1.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at org.bouncycastle.bcpg.BCPGInputStream.read(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream$PartialInputStream.read(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream.read(Unknown Source)
	at org.bouncycastle.util.io.Streams.readFully(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream.readFully(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream.readFully(Unknown Source)
	at org.bouncycastle.bcpg.MPInteger.<init>(Unknown Source)
	at org.bouncycastle.bcpg.SignaturePacket.<init>(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream.readPacket(Unknown Source)
	at org.bouncycastle.openpgp.PGPSignature.<init>(Unknown Source)
	at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at com.test.pgp.bc.BCPGPDecryptor.decryptFile(BCPGPDecryptor.java:157)
	at com.test.pgp.bc.BCPGPDecryptor.decryptFile(BCPGPDecryptor.java:79)
	at com.test.pgp.bc.BCPGPDecryptor.decryptFile(BCPGPDecryptor.java:73)
	at com.test.pgp.bc.BCPGPDecryptor.decryptFile(BCPGPDecryptor.java:69)
	at com.test.pgp.bc.BCPGPTest.decryptSignedFile(BCPGPTest.java:55)
	at com.test.pgp.bc.BCPGPTest.main(BCPGPTest.java:15)

**Comment by huliangshan123** [comment]
this method is decryptSignedFile, please help me

**Comment by huliangshan123** [comment]
thank you very much
